#+title: Daily work log of Sasank Viswanadha

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Getting familiar with git,emacs.
   + What did I get done against each task?
   Browsed around and learnt about version control and git.

** [2016-05-17 Tue]
   Today, We started building a small web application from scratch.  The steps
   in deeveloping a web application were intorduced.  Two of the steps
   undeerstanding the requirements and building the data model.  For building
   the data model we learnt about cardinality and relations.  Using these we
   defined some abstract entry types.  At any point of time these types define
   the state of the system.  The state of the system can be chaged by an
   operation.  On a high level, the operations on the system belonged to
   CRUD.  
- C Create a user.  
- R : Read from a user.  
- U : Update a user.  
- D : Delete a user.
  
   We were asked to build the complete set of operation that can be performed
   on our system.  This is available in web-application
  /src/datamodel/index.org.

** [2016-05-18 Wed]

   Today, We started building the back end of the web application.  Our team
   first came up with a structure (data model) that met the specifications of
   the application.  Then we were given a template to implement this structure
   in the object model.  We were also introduced to the unittest package of
   python.  We completed the implementation of Name,Email,User and Role
   packages.  We designed test cases to check if the code is working properly. 
   
** [2016-05-19 Thu]

   We continued building the back end.  We implemented the Session class which
   has all the methods that can change the state of the system.  We constructed
   all the methods and initialized the system with one user as an admin.  This
   admin can then login to the system an create users and perform other
   alterations to the state of the system.  We started designing test cases to
   test the system.  We are yet to complete writing the test cases.  
   
** [2016-05-20 Fri]

   + What is the task I was assigned today?
     To build the object model.
   + What did I get done against each task?
     Completed building the operations in the sessions class.Added a few extra
     methods in the sessions class which could change the state of the system.
     We then constructed a WebSystem class and moved all the methods that could
     change the state of the system to this class.This was done to follow the
     model of our system. We are yet to complete writing the test cases for these.
   
** 1st week summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   

** [2016-05-23 Mon]

   + What is the task I was assigned today?
     To build the object model of the system.
   + What did I get done against each task?
     We finished writing the test cases of our object model.All the test cases
     were working.

** [2016-05-24 Tue]

   + What is the task I was assigned today?
     To build the Object Relational Model.
   
   + What did I get done against each task?
     We started building the ORM. We were intorduced to SQL,SQlalchemy.We
     learnt how to link the Object Model to a MySQL database using
     SQLAlchemy.We had to make several changes to the Object Model in order to
     persist the User objects in a database.
   
** [2016-05-25 Wed]

   + What is the task I was assigned today?
     To build the Object Relational Model.

   + What did I get done against each task?
     We continued building the ORM.We started writing the test cases to check
     if the ORM was working.

** [2016-05-26 Thu]

   + What is the task I was assigned today?
     To build the REST API.
   
   + What did I get done against each task?
     We completed writing the test cases for the ORM. Then, we were intorduced
     to REST API. We started building the REST for our system using Flask.
   
** [2016-05-27 Fri]

   + What is the task I was assigned today?
     To build the REST API and introduction to front end.
   + What did I get done against each task?
     We completed writing the test cases for the REST API and were intorduced to
     front end tools like html,javascript, and angular JS. We started working
     the front end.
** 2nd week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?

** [2016-05-30 Mon]
   + What is the task I was assigned today?
     We had to implement the front end Model,Control,View(MVC) for the front
     end using javascript.
   + What did I get done against each task?
     We implemented the routers so that they communicate with the corresponding
     view.

** [2016-05-31 Tue]
   + What is the task I was assigned today?
     We had to implement the front end Model,Control,View(MVC) for the front
     end using javascript
   + What did I get done against each task?
     We implemented the view of the front end today.
   
* Month of June
** [2016-06-01 Wed]
   + What is the task I was assigned today?
     We had to implement the front end Model,Control,View(MVC) for the front
     end using javascript
   + What did I get done against each task?
     We implemented the controllers for the front end. We fixed certain other
     issues in the application. We complete the User
     Directory application today.
** [2016-06-02 Thu]
   + What is the task I was assigned today?
     We had to deploy the User Directory application on the base4 machine. 
   + What did I get done against each task?
     We deployed our application twice both manually and using the Auto
     Deployment Service (ADS)
     -Manual 
      We installed all the dependencies on the virtual machine and then
     installed our application and made it run on an apache server.
     -ADS
      We had to write out a spec and the ADS read this spec and deployed tour
     application for us.
     
** [2016-06-03 Fri]
   + What is the task I was assigned today?
     Today we had to present our user directory application
   + What did I get done against each task?
     We presented our application and working test cases.
     It was pointed out that there was an inconsistency in our update user
     function.
     Improvements to be made : We have a lot of functions in the REST and we
     did not implement them in the front. We can implement these functions to
     make the application better.

** 3rd week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   

** [2016-06-06 Mon]
   + What is the task I was assigned today?
     Today we had to understand and write down the datamodel for the existing
     outreach portal.
   + What did I get done against each task?
     We started understanding the model of the outreach portal. We realized the
     flaws of it and started writing the datamodel for this.
     
** [2016-06-07 Tue]
   + What is the task I was assigned today?
     I was on leave today. Reason : Sick
   + What did I get done against each task?
     
** [2016-06-08 Wed]
   + What is the task I was assigned today?
     Today we had to implement the audit class in the user directory
     application.
     
   + What did I get done against each task?
     I started implementing the audit table which logs all the operations done
     to the system. The idea is to implement this in the new outreach portal.

** [2016-06-09 Thu]
   + What is the task I was assigned today?
     Today we had to implement the audit class in the user directory
     application.
   + What did I get done against each task?
     I could not implement the audit class in my User Directory because of
     database lazy load. 

** [2016-06-10 Fri]
   + What is the task I was assigned today?
     Today I was on leave. Reason : out of station
   + What did I get done against each task?

** 4th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   

** [2016-06-13 Mon]
   + What is the task I was assigned today?
     Today we had to try the open Id in the user directory
   + What did I get done against each task?
     We tried implementing and then realised that it dosent meet the
     requirements needed by the outreach portal.
** [2016-06-14 Tue]
   + What is the task I was assigned today?
     Today we had to explore the Google Identity tool kit for the
     authentication of the out reach portal.
   + What did I get done against each task?
     We read through the docs of authentication services offered by google and
     felt that Identity tool kit could meet the requirements of the outreach portal.

** [2016-06-15 Wed]
   + What is the task I was assigned today?
     Today we had to explore the Google Identity tool kit for the
     authentication of the out reach portal.
   + What did I get done against each task?
     We tried out an example of the google identity tool kit but couldnt get it
     working because of some configuration issues.
     We had a meeting where we discussed the new outreach portal.We started
     working on formulating the datamodel for the new outreach portal.

** [2016-06-16 Thu]
   + What is the task I was assigned today?
     Today we had to formulate the datamodel for the new outreach portal. 
   + What did I get done against each task?
     We completed formulating the datamodel for the parts we discussed on
     Wednesday. We had a review and the flaws and the mistakes were pointed out
     to us. We started modifying our model accordingly.

** [2016-06-17 Fri]
   + What is the task I was assigned today?
     Today we had to formulate the datamodel for the new outreach portal.
   + What did I get done against each task?
     We finished making modifications to our model based on the review we had
     on Thursday.

** 5th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   

** [2016-06-20 Mon]
   I was on leave.
  
** [2016-06-21 Tue]
   We started to build the object entities for the new outreach portal. We finished
   building the object entities and started working on the persistent entities.
** [2016-06-22 Wed]
   We continued to work on building the persistent entities for the new outreach portal.

** [2016-06-23 Thu]
   We finished building the persistent entities and started building the object system.
** [2016-06-24 Fri]
   We continued working on the object system and completed the object system.

** 6th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   


** [2016-06-27 Mon]
   We started modifying the entities to suit the requirements of the outreach
   portal 3.0
** [2016-06-28 Tue]
   We had a review today and we had to make all the necessary changes.

** [2016-06-29 Wed]
   Today we made the first release of the outreachportal 3.0. It consisted of
   all the entities that were in the 1st part of the datamodel. Then we made a
   few modifications to Role in object model ( oc-center and nc-center ) which
   we had to include in persistence and also we discussed on how spokes and hub
   should be stored in persistence. All the changes were incorporated and a
   working code of the persistence(entities) was written. I also worked on
   including the hub,spokes relationship between nc and oc.

** [2016-06-30 Thu]
   We modified the object model to include user_status and soft delete and
   continued working on the persistent system.
* Month of July
** [2016-07-01 Fri]
   We finished building the persistent system. But then we realized that having
   two systems one for object model and one for persistent system is code
   duplication and that this should be avoided.


** 7th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   


** [2016-07-04 Mon]
   We modified some things in the persistent system. We had an informal chat
   with the Professor and discussed about the possible solutions for the
   problem we faced on 2016-07-01.
** [2016-07-05 Tue]
   + What is the task I was assigned today?


   + What did I get done against each task?

** [2016-07-06 Wed]
   + What is the task I was assigned today?


   + What did I get done against each task?



** [2016-07-07 Thu]
   + What is the task I was assigned today?

   + What did I get done against each task?


** [2016-07-08 Fri]
   + What is the task I was assigned today?

   + What did I get done against each task?

** 8th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   







** [2016-07-11 Mon]
   + What is the task I was assigned today?
     
   + What did I get done against each task?

** [2016-07-12 Tue]
   + What is the task I was assigned today?


   + What did I get done against each task?

** [2016-07-13 Wed]
   + What is the task I was assigned today?


   + What did I get done against each task?


** [2016-07-14 Thu]
   + What is the task I was assigned today?

   + What did I get done against each task?

** [2016-07-15 Fri]
   + What is the task I was assigned today?

   + What did I get done against each task?

** 9th week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   





