#+title: Daily work log of Sasank Viswanadha

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Getting familiar with git,emacs.
   + What did I get done against each task?
   Browsed around and learnt about version control and git.

** [2016-05-17 Tue]
   Today, We started building a small web application from scratch.  The steps
   in deeveloping a web application were intorduced.  Two of the steps
   undeerstanding the requirements and building the data model.  For building
   the data model we learnt about cardinality and relations.  Using these we
   defined some abstract entry types.  At any point of time these types define
   the state of the system.  The state of the system can be chaged by an
   operation.  On a high level, the operations on the system belonged to
   CRUD.  
- C Create a user.  
- R : Read from a user.  
- U : Update a user.  
- D : Delete a user.
  
   We were asked to build the complete set of operation that can be performed
   on our system.  This is available in web-application
  /src/datamodel/index.org.

** [2016-05-18 Wed]

   Today, We started building the back end of the web application.  Our team
   first came up with a structure (data model) that met the specifications of
   the application.  Then we were given a template to implement this structure
   in the object model.  We were also introduced to the unittest package of
   python.  We completed the implementation of Name,Email,User and Role
   packages.  We designed test cases to check if the code is working properly. 
   
** [2016-05-19 Thu]

   We continued building the back end.  We implemented the Session class which
   has all the methods that can change the state of the system.  We constructed
   all the methods and initialized the system with one user as an admin.  This
   admin can then login to the system an create users and perform other
   alterations to the state of the system.  We started designing test cases to
   test the system.  We are yet to complete writing the test cases.  

   
** [2016-05-20 Fri]

   + What is the task I was assigned today?
     To build the object model.
   + What did I get done against each task?
     Completed building the operations in the sessions class.Added a few extra
     methods in the sessions class which could change the state of the system.
     We then constructed a WebSystem class and moved all the methods that could
     change the state of the system to this class.This was done to follow the
     model of our system. We are yet to complete writing the test cases for these.
   
** 1st week summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   

** [2016-05-23 Mon]

   + What is the task I was assigned today?
     To build the object model of the system.
   + What did I get done against each task?
     We finished writing the test cases of our object model.All the test cases
     were working.

   
** [2016-05-24 Tue]

   + What is the task I was assigned today?
     To build the Object Relational Model.
   
   + What did I get done against each task?
     We started building the ORM. We were intorduced to SQL,SQlalchemy.We
     learnt how to link the Object Model to a MySQL database using
     SQLAlchemy.We had to make several changes to the Object Model in order to
     persist the User objects in a database.
   
** [2016-05-25 Wed]

   + What is the task I was assigned today?
     To build the Object Relational Model.

   + What did I get done against each task?
     We continued building the ORM.We started writing the test cases to check
     if the ORM was working.

   
** [2016-05-26 Thu]

   + What is the task I was assigned today?
     To build the REST API.
   
   + What did I get done against each task?
     We completed writing the test cases for the ORM. Then, we were intorduced
     to REST API. We started building the REST for our system using Flask.
   
** [2016-05-27 Fri]

   + What is the task I was assigned today?
     To build the REST API and introduction to front end.
   + What did I get done against each task?
     We completed writing the test cases for the REST API and were intorduced t
     front end tools like html,javascript, and angular JS. We started working
     the front end.
** 2nd week Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
* Month of June
* Month of July
